# Generated by Django 5.1.5 on 2025-04-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("base_price", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                ("discount_order", models.IntegerField(default=0)),
                ("discount_percentage", models.IntegerField(default=0)),
                ("image1", models.TextField(null=True)),
                ("image2", models.TextField(null=True)),
                ("image3", models.TextField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=5)),
                ("name", models.CharField(max_length=255)),
                ("description_title", models.TextField()),
                ("description_text", models.TextField()),
                ("benefits", models.JSONField()),
                ("functionalities", models.JSONField()),
                ("specifications", models.JSONField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
