# Generated by Django 5.1.5 on 2025-04-16 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_productdetails_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetails",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="shop.product",
            ),
        ),
    ]
