# Generated by Django 5.1.5 on 2025-04-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproduct",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="discount",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartProduct",
        ),
        migrations.DeleteModel(
            name="Discount",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderProduct",
        ),
    ]
