# Generated by Django 5.1.5 on 2025-04-16 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_productdetails_name_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.product"
            ),
        ),
    ]
