# Generated by Django 5.1.5 on 2025-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_order_billing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_id",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_monthly_price_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_yearly_price_id",
            field=models.TextField(null=True),
        ),
    ]
