# Generated by Django 5.1.5 on 2025-04-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_product_stripe_id_product_stripe_monthly_price_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
        migrations.AddField(
            model_name="category",
            name="global_name",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="CategoryLocale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale", models.TextField()),
                ("name", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locales",
                        to="shop.category",
                    ),
                ),
            ],
        ),
    ]
