# Generated by Django 5.1.5 on 2025-05-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_category_name_category_global_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="base_price",
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="benefits",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="functionalities",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="specifications",
            field=models.TextField(),
        ),
    ]
