# Generated by Django 5.1.5 on 2025-05-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_remove_product_base_price_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetails",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="shop.product",
            ),
        ),
    ]
