# Generated by Django 5.1.5 on 2025-05-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_productdetails_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="recurrence",
            field=models.IntegerField(default=0),
        ),
    ]
