# Generated by Django 5.1.5 on 2025-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_order_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_price",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
