# Generated by Django 5.1.5 on 2025-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_product_base_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="recurrence",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="recurring",
            field=models.IntegerField(default=0),
        ),
    ]
