# Generated by Django 5.1.5 on 2025-06-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_remove_order_recurrence_orderitem_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price_at_sale",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
