# Generated by Django 5.1.5 on 2025-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_id",
            field=models.TextField(null=True),
        ),
    ]
