# Generated by Django 5.1.5 on 2025-03-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(max_length=100),
        ),
    ]
