# Generated by Django 5.1.5 on 2025-05-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="recurrence",
            field=models.BooleanField(default=False),
        ),
    ]
