# Generated by Django 5.1.5 on 2025-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_subscription_payment_method_subscription_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="recurrence",
            field=models.IntegerField(default=0),
        ),
    ]
