# Generated by Django 5.1.5 on 2025-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_subscription_status_alter_subscription_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionitem",
            name="stripe_item_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
