# Generated by Django 5.1.5 on 2025-05-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_remove_subscription_current_period_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_invoice_url",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
