# Generated by Django 5.1.5 on 2025-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_payment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="invoice_url",
            field=models.CharField(
                blank=True, default=None, max_length=2000, null=True
            ),
        ),
    ]
